/* Generated by S-function Builder */
#ifndef _GETGYRODATA_BUS_H_
#define _GETGYRODATA_BUS_H_
/* Read only - STARTS */
#ifdef MATLAB_MEX_FILE
#include "tmwtypes.h"
#else
#include "rtwtypes.h"
#endif




#ifndef _DEFINED_TYPEDEF_FOR_gyroData_
#define _DEFINED_TYPEDEF_FOR_gyroData_ 
typedef struct {
  int16_T accl[3];
  int16_T gyro[3];
  real_T temp;
} gyroData;
#endif

/* Read only - ENDS */


#endif
